name: "Destroy Preview Environment"
description: "Destroy preview environments"
inputs:
  name: 
    description: "The name of the preview environment to delete"
    required: true
  log-level:
    description: "Log level string. Valid options are debug, info, warn, error"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
    - ${{ inputs.log-level }}
branding:
  color: 'green'
  icon: 'grid'
