name: "Destroy Preview Environment"
description: "Destroy preview environments"
inputs:
  name: 
    description: "The name of the preview environment to delete"
    required: true
  file:
    description: "The name of the okteto manifest file to use in the destroy operation"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
branding:
  color: 'green'
  icon: 'grid'
